trigger:
- none

pool:
  name: default

variables:
 - group: packer-terraform-image-build-variables

steps:

- task: PowerShell@2
  inputs:
    azureSubscription: 'AkManagedIdentity'
    scriptType: 'powershell@2'
    scriptLocation: 'inlineScript'
    inlineScript: |
      try {
      
        Write-Output "Terraform version:"
        terraform version

        Write-Output "Running terraform init..."
        terraform init

        Write-Output "Running terraform plan..."
        terraform plan

        Write-Output "Applying terraform..."
        terraform apply -auto-approve
      } catch {
        Write-Output "An error occurred: $_"
        exit 1
      }
  displayName: 'Install and Run terraform'
  env:
    TF_VAR_winrm_password: $(WINRM_PASSWORD)
    TF_VAR_domain_password: $(DOMAIN_PASSWORD)
