trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AkManagedIdentity'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |

      echo "Installing terraform ..."
      sudo apt-get update -y
      sudo apt-get install -y terraform

      echo "terraform version:"
      terraform version

      echo "Running terraform init..."
      terraform init .
      echo "Running terraform plan..."
      terraform plan main.tf
      terraform apply -auto-approve

  displayName: 'Install and Run terraform'
  env:
    TF_VAR_winrm_password: $(WINRM_PASSWORD)
    TF_VAR_domain_password: $(DOMAIN_PASSWORD)
